version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=movies_db
    restart: unless-stopped
  corujao:
    image: corujao_2.0
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: corujao_2.0
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - db
volumes:
  postgres-data:
